version: '3.8'

services:
  # Aplicação principal
  banko-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: banko-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - banko-network

  # Ambiente de desenvolvimento
  banko-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: banko-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    profiles:
      - dev
    networks:
      - banko-network

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    container_name: banko-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - banko-app
    profiles:
      - production
    networks:
      - banko-network

networks:
  banko-network:
    driver: bridge

volumes:
  node_modules:
  next_cache: 